config/routes.rb
HackdayVoting::Application.routes.draw do
  resources :hack_days, only: [:create, :new, :show]
  resources :projects, only: [:update]
  root 'static_pages#home'

end

app/models/hack_day.rb
class HackDay < ActiveRecord::Base
	has_many :projects, dependent: :destroy
	validates :title, presence: true
	default_scope -> { order('created_at DESC') }
end

app/models/project.rb
class Project < ActiveRecord::Base
	belongs_to :hack_day
  	validates :hack_day_id, :value,  presence: true
  	default_scope -> { order('id ASC') }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/hack_days_controller.rb
class HackDaysController < ApplicationController
  def new
    @projects = [""]
  end

  def show
    if (@hack_day = HackDay.find_by_id(params[:id]))
      session["remaining_vote#{params[:id]}"] ||= 3
      @votes_left = session["remaining_vote#{params[:id]}"]
    else
      redirect_to "/404.html"
    end
  end

  def create
    @title = params[:title]
    @new_hack_day = HackDay.new(title: @title)
    @projects = params[:projects]
    @projects.select!(&:present?)
    if(@projects.length >= 2)
      unless @new_hack_day.save
        flash.now[:error] = "Enter a title"
        render "new" and return
      end
      @projects.each do |x|
        @new_hack_day.projects.create(value: x.strip)
      end
      flash[:notice] = "Vote Creation Successfull"
      redirect_to @new_hack_day
    else
      flash.now[:error] = "Make sure to have two or more options"
      render "new"
    end
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def update
  	if session["remaining_vote#{params[:id]}"] > 0
      if !params[:vote].blank?
        Project.increment_counter(:num_votes, params[:vote])
        session["remaining_vote#{params[:id]}"] -= 1
        flash[:notice] = "Vote Successfull"
      else
        flash[:error] = "Select an option"
      end
    else
      flash[:error] = "You are out of votes"
    end
    redirect_to hack_day_path(params[:id])
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hack_days_helper.rb
module HackDaysHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/hack_days/new.html.erb
<% provide(:title,"New Vote") %>
<div class="center hero-unit">
  <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>"><%= value %></div>
  <% end %>
  <h1>New Vote</h1>
  <%= form_tag(hack_days_path, method: "post") do %>
    <%= label_tag :title, "Title"%>
    <%= text_field_tag :title, "#{@title}" %>
    <div id="Projects">
      <%= label_tag "projects[]", "Enter the vote options below, comma seperated" %>
      <% @projects.each do |string| %>
        <%= label_tag "projects[]", " " %>
        <%= text_field_tag "projects[]", "#{string}"%>
      <% end %>
    </div>
    <a href="javascript:;" id="addProject">Add More Projects</a>
    <br>
    <%= submit_tag("Create Vote", class: "btn btn-large btn-primary") %>
  <% end %> 
</div>

<div class="hide" id="new_projects">
  <%= label_tag "projects[]", " " %>
  <%= text_field_tag "projects[]" %>
</div>

<script>
$(document).ready(function(){
  $("#addProject").click(function(){
    $("#Projects").append($("#new_projects").html());
  });
});
</script>

app/views/hack_days/show.html.erb
<% provide(:title,@hack_day.title) %>
<div class="center hero-unit">
  <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>"><%= value %></div>
  <% end %>
  <h1><%= @hack_day.title %></h1>
  <h2>Vote Below, <%=@votes_left%> votes left</h2>
  <%= form_tag(project_path(@hack_day.id),method: "put") do %>
    <% @hack_day.projects.each do |x| %>
      <%= radio_button_tag(:vote, x.id) %>
      <%= label_tag(x.value.to_sym, "#{x.value} -- #{x.num_votes}") %>
    <% end %>
    <%= submit_tag "Vote", class: "btn btn-large btn-primary" %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hack Day Voting | <%=yield(:title) %></title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
  </head>
  <body>
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="navbar-inner">
        <div class="container">
          <%= link_to "Hack Day Voting", root_path , id: "logo" %>
          <nav>
            <ul class="nav pull-right">
              <li><%= link_to "Home",    root_path %></li>
              <li><%= link_to "New Vote",  new_hack_day_path  %></li>
            </ul>
          </nav>
        </div>
      </div>
    </header>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/static_pages/home.html.erb
<% provide(:title,"Home") %>
<div class="center hero-unit">
  <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>"><%= value %></div>
  <% end %>
  <h1>Welcome</h1>
  <p>Welcome to the HackDay voting page, Vote below, or make a new Vote!</p>
  <% if HackDay.any? %>
    <table style="width:500px"
      <tr>
        <th>Vote Name</th>
        <th>Created At</th>
      </tr>
      <%HackDay.all.each do |x|%>
        <tr>
          <td><%=link_to(x.title,hack_day_path(x.id))%></td>
          <td><%=x.created_at %></td>
        </tr>
      <% end %>
    </table>
  <% end %>
</div>